"""Deterministic classification labels for triage candidates."""

AUTH_SURFACE = "auth_surface"
ADMIN_SURFACE = "admin_surface"
ENVIRONMENT_SURFACE = "environment_surface"
API_SURFACE = "api_surface"
FILE_OR_CONTENT_SURFACE = "file_or_content_surface"
OBJECT_REFERENCE_REVIEW = "object_reference_review"
REDIRECT_PARAMETER_REVIEW = "redirect_parameter_review"
TECHNOLOGY_REVIEW = "technology_review"
MANUAL_NOTE_REVIEW = "manual_note_review"
LOW_SIGNAL_STATIC = "low_signal_static"
KILL_SWITCH = "kill_switch"
