"""Deterministic classification labels for triage candidates."""

AUTH_SURFACE = "auth_surface"
ADMIN_SURFACE = "admin_surface"
ENVIRONMENT_SURFACE = "environment_surface"
API_SURFACE = "api_surface"
FILE_OR_CONTENT_SURFACE = "file_or_content_surface"
OBJECT_REFERENCE_REVIEW = "object_reference_review"
REDIRECT_PARAMETER_REVIEW = "redirect_parameter_review"
TECHNOLOGY_REVIEW = "technology_review"
MANUAL_NOTE_REVIEW = "manual_note_review"
LOW_SIGNAL_STATIC = "low_signal_static"
KILL_SWITCH = "kill_switch"
HIGH_PORT_HTTP_SERVICE = "high_port_http_service"
MULTIPLE_HTTP_SERVICES = "multiple_http_services"
ROBOTS_ARTIFACT = "robots_artifact"
HIDDEN_PATH_REVIEW = "hidden_path_review"
ENCODED_ARTIFACT_REVIEW = "encoded_artifact_review"
CREDENTIAL_LIKE_ARTIFACT_REVIEW = "credential_like_artifact_review"
LAB_MARKER_ARTIFACT = "lab_marker_artifact"
EXPOSED_SERVICE_CONTEXT = "exposed_service_context"
DEAD_LOW_SIGNAL_PATH = "dead_low_signal_path"
