"""Recon mode documentation contract checks."""

from __future__ import annotations

from pathlib import Path


def test_recon_modes_design_contract_exists_and_covers_required_terms() -> None:
    path = Path(__file__).resolve().parents[1] / "docs" / "RECON_MODES.md"
    assert path.is_file()

    content = path.read_text(encoding="utf-8")
    lowered = content.lower()

    for expected in (
        "Quick Recon",
        "Standard Recon",
        "Deep Recon",
        "`lab-safe-tiny`",
        "`standard-bounded`",
        "`deep-bounded`",
        "authorisation",
        "strict scope",
        "Global Forbidden Behaviours",
        "Vulnerability Intelligence Later",
        "Optional LLM Review Later",
        "unsupported vulnerability claims",
        "CTF/lab",
        "Local Evidence Mode",
        "hash-looking artefact",
        "encoding",
        "robots.txt",
        "Hidden HTML",
        "evidence chain",
        "Bounded nested discovery",
        "Cron Misconfiguration",
        "Standard Recon v1",
        "Manual Review Leads",
        "already-collected evidence",
        "ArtefactSource",
        "offline interpretation collector",
        "does not increase scan volume",
        "does not mean bigger wordlists",
        "does not mean recursive crawling",
        "not proof of vulnerability",
        "Standard Recon v1 is now available",
        "does not fetch extra pages",
        "Deep Recon remains unavailable",
        "Deep Recon v1 design contract",
        "aggressive evidence discovery inside strict authorisation, scope, method, and rate limits",
        "genuine step up from Standard",
        "expanded bounded collection",
        "bounded second-pass content discovery",
        "shallow same-origin crawl",
        "same-origin JavaScript/source file collection as text only",
        "static route extraction",
        "static parameter inventory",
        "HTML form inventory without submitting forms",
        "source map detection",
        "deeper correlation",
        "must not increase attack behaviour",
        "Brute forcing live services",
        "Password spraying",
        "Credential stuffing",
        "Authentication testing",
        "Form submission",
        "Browser automation that interacts with applications",
        "JavaScript execution",
        "`sqlmap`",
        "`hydra`",
        "`masscan`",
        "Deep Recon must remain unavailable until all of these gates exist",
        "Tests proving Quick remains unchanged",
        "Tests proving Standard remains unchanged",
        "Tests proving Deep has explicit bounds",
        "Tests proving Deep unavailable state is intentional until enabled",
        "Code-level planned profile contract and explicit bounds model",
        "code-level planned-pipeline skeleton",
        "static contract data only",
        "does not make `deep-bounded` executable",
        "code-level planned output and artefact taxonomy",
        "does not create output files",
        "does not create evidence packs",
        "code-level scope and safety preflight contract",
        "planned gates for authorisation",
        "does not inspect projects",
        "does not read or write project files",
        "static Deep Recon readiness summary renderer",
        "combines the Deep profile contract, explicit bounds, planned pipeline, planned",
        "static contract rendering only",
        "`bugslyce recon deep-readiness`",
        "static contract Markdown to stdout only",
        "does not run Deep Recon",
        "does not change mode availability",
        "machine-readable Deep Recon readiness snapshot",
        "`bugslyce recon deep-readiness --json`",
        "contract snapshot as JSON to stdout only",
        "validation status as the Markdown renderer",
        "pure internal Deep Recon eligibility evaluator",
        "explicit operator-provided facts",
        "targets, does not read or write project files",
        "does not expose a CLI command",
        "`bugslyce recon deep-eligibility`",
        "fails closed",
        "explicit operator-provided facts plus static contract",
        "`bugslyce recon deep-eligibility --json`",
        "pure internal Deep common metadata request planner",
        "bounded deterministic queue for common metadata files",
        "does not fetch URLs",
        "does not expose a CLI command",
        "`bugslyce recon deep-metadata-plan`",
        "explicit service URLs only",
        "`bugslyce recon deep-metadata-plan --json`",
        "does not inspect targets",
        "pure internal adapter from already-loaded BugSlyce",
        "project-state HTTP service, endpoint, HTTP artefact, and discovered-path data",
        "in-memory project state",
        "Standard Human Triage Brief",
        "readable evidence cards",
        "generic signals such as login/admin/auth surfaces",
        "report UX only",
        "does not replace manual validation",
        "bounded Standard auth-surface route discovery",
        "`standard-bounded-core`",
        "keeps every `lab-root-tiny` general",
        "preserves existing tiny/root coverage",
        "small deterministic",
        "Quick remains lighter",
        "Standard remains selected by `standard-bounded`",
        "recognise `standard-bounded-core` content discovery artefacts",
        "ordinary login form structure",
        "auth-route context rather than credential discovery",
        "`bugslyce recon deep-metadata-review --input-dir",
        "renders the offline metadata review to stdout",
        "creates no artefacts",
        "offline Deep metadata coverage summary model",
        "planned but uncollected metadata URLs",
        "does not fetch URLs, create outputs, add CLI",
        "`bugslyce recon deep-metadata-coverage --input-dir",
        "offline coverage/gap analysis to stdout",
        "creates no artefacts, does not execute Deep Recon",
        "suppresses duplicate-origin planner skip noise",
        "planner-origin skips, not missing metadata coverage",
        "offline Deep source/route coverage model",
        "source, route, body, header, static, and metadata context",
        "no CLI exposure in this phase",
        "`bugslyce recon deep-source-route-coverage --input-dir",
        "offline source/route coverage to stdout",
        "read-only and stdout-only",
        "Bare static directories are treated as static/directory context",
        "long evidence lists are compacted",
        "classification and reporting polish only",
        "offline Deep preview bundle model",
        "metadata review, metadata coverage, and source/route coverage",
        "bounded manual review priorities",
        "internal/model-only in this phase",
        "`bugslyce recon deep-preview --input-dir",
        "combined offline Deep bundle to stdout",
        "read-only and stdout-only",
        "Low-priority metadata coverage gaps are grouped",
        "route and clue priorities remain prominent",
        "metadata coverage counts are preserved",
        "offline Deep collection policy model",
        "restrictive request bounds",
        "blocks unsafe methods and intents",
        "offline Deep collection request planner",
        "proposes future collection requests from existing local evidence",
        "evaluates every proposed request through the restrictive Deep collection policy",
        "bounded Deep metadata collector core",
        "policy-allowed metadata requests through an explicit injected fetcher",
        "does not crawl, submit forms, authenticate, brute",
        "bounded Deep HTTP fetcher transport primitive",
        "standard-library HTTP only",
        "Redirects are not automatically followed",
        "HTTP error responses are returned as bounded responses",
        "`bugslyce recon deep-metadata-collect --input-dir",
        "fetches only policy-allowed metadata coverage requests",
        "prints the in-memory result to stdout",
        "writes no artefacts, creates no directories",
        "does not collect routes, crawl, submit forms",
        "`--write-artifacts`",
        "`deep_metadata_collection.md`",
        "`deep_metadata_collection.json`",
        "not full response bodies",
        "offline Deep metadata collection review summary",
        "status buckets, repeated body",
        "makes no HTTP requests and writes no artefacts",
        "`bugslyce recon deep-metadata-collection-review --input-dir",
        "reads the existing `deep_metadata_collection.json` artefact",
        "prints the offline review summary to stdout",
        "skipped request reasons",
        "bounded Deep source/route collector core",
        "policy-allowed `source_route_coverage` requests",
        "without storing full response bodies",
        "skips metadata requests, policy-blocked requests, query-string URLs",
        "adds no CLI",
        "makes no direct HTTP requests",
        "`bugslyce recon deep-source-route-collect --input-dir",
        "collects only policy-allowed `source_route_coverage` requests",
        "prints the bounded result to stdout",
        "artefacts and creates no directories",
        "collect query-string URLs",
        "renderer-only preview compaction",
        "readability without changing stored previews",
        "without changing stored previews, hashes, byte counts",
        "collection decisions, CLI options, or write artefacts",
        "`deep-source-route-collect` stdout-only by default",
        "`deep_source_route_collection.md`",
        "`deep_source_route_collection.json`",
        "JSON stores bounded previews, hashes, byte counts",
        "not full response bodies",
        "does not create nested directories",
        "offline Deep source/route collection review summary",
        "deterministic manual review leads",
        "login redirects",
        "cookie-on-redirect signals",
        "forbidden admin/status routes",
        "repeated body signatures",
        "query-string skips",
        "metadata skips",
        "skip reason counts",
        "does not fetch anything",
        "load or write files",
        "`bugslyce recon deep-source-route-collection-review --input-dir",
        "reads the existing `deep_source_route_collection.json` artefact",
        "reconstructs the Deep source/route collection result",
        "prints the offline review summary to stdout",
        "writes no files",
        "makes no HTTP requests",
        "modify collection artefacts",
        "offline Deep post-collection review bundle model",
        "existing metadata and source/route collection review summaries",
        "bounded unified review priorities",
        "model and renderer only",
        "performs no file or network IO",
        "does not call collectors",
        "`bugslyce recon deep-collection-review-bundle --input-dir",
        "reads existing Deep collection JSON artefacts",
        "supports either or both metadata and source/route collection artefacts",
        "prints the unified review bundle to stdout",
        "writes no files",
        "makes no network requests",
        "offline Deep HTTP fingerprint summary model",
        "already-collected metadata and source/route HTTP response evidence",
        "titles observed in bounded previews",
        "content types, servers",
        "cookie presence, exact body hashes",
        "cautious header observations",
        "does not perform auth-flow analysis or fuzzy similarity grouping",
        "offline one-hop redirect/auth-flow review model",
        "existing redirect fingerprint evidence",
        "relative and absolute Location forms",
        "same-origin and cross-origin relationships",
        "lexical auth-looking path transitions",
        "cookie presence on redirects without retaining cookie values",
        "strips query values, fragment contents, and URL userinfo",
        "follows no redirects",
        "does not attempt authentication",
        "offline Deep response similarity review model",
        "groups existing HTTP fingerprints using conservative deterministic",
        "carries forward exact repeated-body groups",
        "groups repeated redirect patterns",
        "groups repeated client-error and response signatures",
        "candidate default/template patterns",
        "unique ungrouped 2xx responses for comparison",
        "does not fetch responses or follow redirects",
        "does not confirm soft 404s",
        "default pages, or semantic identity",
        "offline Deep HTML route extraction model",
        "parses full HTML bodies already retained by in-memory Deep collection results",
        "does not use truncated previews as extraction input",
        "allowlisted `href`, `src`, and `data` references",
        "resolves and sanitises HTTP/HTTPS routes",
        "strips URL credentials, query values, and fragment contents",
        "groups duplicate references deterministically",
        "does not fetch or follow extracted routes",
        "does not inspect JavaScript contents",
        "does not inventory forms",
        "offline Deep JavaScript route extraction model",
        "lexically inspects full JavaScript response bodies and inline JavaScript",
        "does not use bounded previews as extraction input",
        "complete static route-like string literals",
        "does not execute JavaScript or evaluate expressions",
        "skips dynamic templates and concatenated partial strings",
        "sanitises URL credentials, query values, and fragment",
        "ambiguous relative strings without assuming browser",
        "aggregates duplicate candidates deterministically",
        "bounded Deep shallow route follow-up model",
        "deterministic bounded plan from same-origin 91A and 91B routes",
        "removes query strings from actual request URLs",
        "query parameter names as metadata only",
        "one shallow `GET` pass through an injected bounded fetcher",
        "makes no recursive requests",
        "does not manually follow redirects",
        "does not submit forms or mutate parameters",
        "bounded response summaries and in-memory full bodies",
        "adds no export or CLI seam",
        "offline Deep form inventory model",
        "original and shallow-follow-up HTML bodies",
        "uses full in-memory bodies rather than previews",
        "sanitised action, method, enctype, target kind",
        "aggregate control-type/count metadata",
        "without retaining field names or values",
        "does not submit forms or fetch actions",
        "performs no network or file IO",
        "adds no CLI, export, report, or orchestration seam",
        "individual parameter-name inventory to Phase 92B",
        "offline Deep parameter-name inventory model",
        "original and shallow HTML form controls",
        "form-action queries, route-extraction metadata",
        "collected URL metadata",
        "uses full in-memory HTML bodies rather than previews",
        "preserves case-sensitive names",
        "aggregates contexts and provenance deterministically",
        "retains names only and never values",
        "performs no replay, guessing, mutation, submission",
        "action fetching, network or file IO",
        "optional report-rendering seam for already-rendered Deep",
        "When the seam is unused, the report is unchanged",
        "does not build, collect, read, or render Deep results itself",
        "evidence-pack, runbook, or orchestration integration",
        "passive inclusion seams for already-existing Deep outputs",
        "explicitly supplied existing Deep files",
        "optional runbook seam for already-rendered Deep Markdown",
        "does not discover, build, parse, or render Deep results",
        "pipeline orchestration",
        "adds no CLI option",
        "deterministic orchestration over already-completed bounded Deep",
        "composes existing offline Deep review stages",
        "produces report, runbook, and explicit evidence-pack payloads",
        "collection or network requests itself",
        "adds no CLI or automatic pipeline",
    ):
        assert expected.lower() in lowered

    for forbidden_boundary in (
        "Do not add `shell=True`",
        "Do not add `subprocess.Popen`",
        "Do not add `os.system`",
        "Do not add `pexpect`",
        "Do not add arbitrary command execution",
    ):
        assert forbidden_boundary in content
